userService:
  replicaCount: 1
  image:
    repository: ghcr.io/elshinsergei/user-service
    tag: latest
  service:
    port: 8081
  virtualService:
    timeout: 3s
    retries:
      attempts: 3
      perTryTimeout: 1s
  resources:
    requests:
      memory: "250Mi"
      cpu: "200m"
    limits:
      memory: "500Mi"
      cpu: "800m"

bookingService:
  replicaCount: 1
  image:
    repository: ghcr.io/elshinsergei/booking-service
    tag: latest
  service:
    port: 8082
  resources:
    requests:
      memory: "300Mi"
      cpu: "200m"
    limits:
      memory: "600Mi"
      cpu: "800m"

notificationService:
  replicaCount: 2
  image:
    repository: ghcr.io/elshinsergei/notification-service
    tag: latest
  service:
    port: 8083
  resources:
    requests:
      memory: "200Mi"
      cpu: "200m"
    limits:
      memory: "400Mi"
      cpu: "800m"

gateway:
  enabled: true
  host: "*"

prometheus:
  serviceAccounts:
    server:
      create: true
      name: prometheus-server

kiali-server:
  auth:
    strategy: "anonymous" # Для локальной разработки без логина
  deployment:
    accessible_namespaces:
      - "default"
  external_services:
    prometheus:
      # Указываем имя сервиса, который создаст Helm-чарт Prometheus
      url: "http://salon-app-prometheus-server.default.svc.cluster.local:80"
    istio:
      root_namespace: "istio-system"
