userService:
  replicaCount: 1
  image:
    repository: user-service
    tag: latest
  service:
    port: 8081
  virtualService:
    timeout: 3s
    retries:
      attempts: 3
      perTryTimeout: 1s

bookingService:
  replicaCount: 1
  image:
    repository: booking-service
    tag: latest
  service:
    port: 8082

notificationService:
  replicaCount: 1
  image:
    repository: notification-service
    tag: latest
  service:
    port: 8083

gateway:
  enabled: true
  host: "*"

prometheus:
  serviceAccounts:
    server:
      create: true
      name: prometheus-server

kiali-server:
  auth:
    strategy: "anonymous" # Для локальной разработки без логина
  deployment:
    accessible_namespaces:
      - "default"
  external_services:
    prometheus:
      # Указываем имя сервиса, который создаст Helm-чарт Prometheus
      url: "http://salon-app-prometheus-server.default.svc.cluster.local:80"
    istio:
      root_namespace: "istio-system"
