apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: {{ .Values.bookingService.replicaCount }}
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: {{ .Values.bookingService.image.repository }}:{{ .Values.bookingService.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.bookingService.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://booking-db:5432/booking_db
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq

---
# 2. Service
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  ports:
    - port: {{ .Values.bookingService.service.port }}
      targetPort: {{ .Values.bookingService.service.port }}
      name: http
  selector:
    app: booking-service