apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: {{ .Values.notificationService.replicaCount }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: {{ .Values.notificationService.image.repository }}:{{ .Values.notificationService.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.notificationService.service.port }}
          resources:
            {{- toYaml .Values.notificationService.resources | nindent 12 }}
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /actuator/health*/}}
{{/*              port: {{ .Values.notificationService.service.port }}*/}}
{{/*            initialDelaySeconds: 40*/}}
{{/*            periodSeconds: 10*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /actuator/health*/}}
{{/*              port: {{ .Values.notificationService.service.port }}*/}}
{{/*            initialDelaySeconds: 60*/}}
{{/*            periodSeconds: 10*/}}
{{/*            failureThreshold: 5*/}}
---
# 2. Service
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  ports:
    - port: {{ .Values.notificationService.service.port }}
      targetPort: {{ .Values.notificationService.service.port }}
      name: http
  selector:
    app: notification-service