apiVersion: v1
kind: Service
metadata:
  name: user-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: user-db
  clusterIP: None # Headless service для StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db
spec:
  serviceName: "user-db"
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: user-db
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: user_db
            - name: POSTGRES_USER
              value: elshin_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-passwords
                  key: user-db-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: user-db-data # Имя из volumeClaimTemplates
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: user-db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi