name: Java CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Важно: нужно для пуша в GitHub Container Registry

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Запускаем сборку и тесты
      - name: Build and Test
        run: mvn clean install -Dtestcontainers.enabled=true

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

            # Сборка и пуш для каждого сервиса
      - name: Build and Push Docker Images
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        run: |
          # Преобразуем имя репозитория в нижний регистр
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          
          # Собираем образы, используя переменную REPO_NAME
          docker build --target user-service -t ghcr.io/$REPO_NAME/user-service:latest .
          docker build --target booking-service -t ghcr.io/$REPO_NAME/booking-service:latest .
          docker build --target notification-service -t ghcr.io/$REPO_NAME/notification-service:latest .
          
          # Пушим их
          docker push ghcr.io/$REPO_NAME/user-service:latest
          docker push ghcr.io/$REPO_NAME/booking-service:latest
          docker push ghcr.io/$REPO_NAME/notification-service:latest



